FROM smebberson/alpine-nginx-nodejs

RUN npm install -g create-react-app

COPY musicbot-ui /ui
WORKDIR /ui
COPY musicbot-ui/src/config/globalConfigs.template /ui/src/config/globalConfigs.js
RUN npm install
RUN npm run build

COPY musicbot-ui/nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 80

# The following isn't needed as the base image manages nginx itself
#CMD nginx